# Generated by Django 5.0.1 on 2025-11-30 22:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Hex color code for visual distinction",
                        max_length=7,
                    ),
                ),
                (
                    "is_ai_suggested",
                    models.BooleanField(
                        default=False, help_text="Was this tag suggested by AI?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Quote Tag",
                "verbose_name_plural": "Quote Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("want_to_read", "Want to Read"),
                            ("currently_reading", "Currently Reading"),
                            ("read", "Read"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="want_to_read",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateField(blank=True, null=True)),
                ("finished_at", models.DateField(blank=True, null=True)),
                (
                    "current_page",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Rating from 1 to 5",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "review",
                    models.TextField(blank=True, help_text="Personal review/thoughts"),
                ),
                (
                    "is_favorite",
                    models.BooleanField(
                        default=False, help_text="Mark as favorite book"
                    ),
                ),
                (
                    "quotes_count",
                    models.IntegerField(
                        default=0, help_text="Number of quotes extracted from this book"
                    ),
                ),
                (
                    "depth_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Engagement score: quotes_count / pages * factors",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Show this book on public profile"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Book",
                "verbose_name_plural": "User Books",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(help_text="The actual quote text")),
                (
                    "page_number",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "chapter",
                    models.CharField(
                        blank=True, help_text="Chapter name or number", max_length=200
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Your personal thoughts/reflections on this quote",
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(
                        default=False, help_text="Mark as favorite quote"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Share publicly (on profile)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="books.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote",
                "verbose_name_plural": "Quotes",
                "ordering": ["-created_at"],
            },
        ),
    ]
