# Generated by Django 5.0.1 on 2025-11-30 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        ("reading", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quotetag",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quote_tags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="quotes", to="reading.quotetag"
            ),
        ),
        migrations.AddField(
            model_name="userbook",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_books",
                to="books.book",
            ),
        ),
        migrations.AddField(
            model_name="userbook",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_books",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="user_book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="reading.userbook",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quotetag",
            unique_together={("user", "slug")},
        ),
        migrations.AddIndex(
            model_name="userbook",
            index=models.Index(
                fields=["user", "status"], name="reading_use_user_id_6b10db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbook",
            index=models.Index(
                fields=["user", "is_favorite"], name="reading_use_user_id_9e3b3f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userbook",
            unique_together={("user", "book")},
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["user", "book"], name="reading_quo_user_id_9e8973_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["user", "is_favorite"], name="reading_quo_user_id_7ac028_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["-created_at"], name="reading_quo_created_09b16c_idx"
            ),
        ),
    ]
