# Generated by Django 5.0.1 on 2025-12-28 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('reading', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='book_author',
            field=models.CharField(blank=True, help_text='Book author (if not linked to database book)', max_length=500),
        ),
        migrations.AddField(
            model_name='quote',
            name='book_title',
            field=models.CharField(blank=True, help_text='Book title (if not linked to database book)', max_length=500),
        ),
        migrations.AlterField(
            model_name='quote',
            name='book',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to book in database', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='books.book'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='user_book',
            field=models.ForeignKey(blank=True, help_text="Optional: Link to user's book entry", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='reading.userbook'),
        ),
    ]
