# Generated by Django 5.0.1 on 2025-12-28 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_quote_book_author_quote_book_title_alter_quote_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Rating from 0.5 to 10.0 (half-star increments)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
