# Generated by Django 5.0.1 on 2025-12-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_alter_userbook_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='chapter',
            field=models.CharField(blank=True, help_text='Chapter name or number', max_length=200, null=True),
        ),
    ]
