# Generated by Django 5.0.1 on 2026-01-01 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('reading', '0005_alter_quote_chapter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text="e.g., 'John 3:16', 'Chapter 5', 'Page 142', 'Letter 12'", max_length=255)),
                ('note_type', models.CharField(choices=[('note', 'Note'), ('quote', 'Quote'), ('question', 'Question'), ('insight', 'Insight')], default='note', max_length=20)),
                ('content', models.TextField(help_text='The note content (supports markdown)')),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('chapter', models.CharField(blank=True, max_length=100)),
                ('is_promoted_to_quote', models.BooleanField(default=False, help_text='Whether this study note has been promoted to a main quote')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_notes', to='books.book')),
                ('promoted_quote', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_study_note', to='reading.quote')),
                ('tags', models.ManyToManyField(blank=True, related_name='study_notes', to='reading.quotetag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_notes', to=settings.AUTH_USER_MODEL)),
                ('user_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_notes', to='reading.userbook')),
            ],
            options={
                'ordering': ['reference', '-created_at'],
                'indexes': [models.Index(fields=['user', 'book'], name='reading_stu_user_id_09e214_idx'), models.Index(fields=['reference'], name='reading_stu_referen_e14668_idx'), models.Index(fields=['note_type'], name='reading_stu_note_ty_1ca442_idx')],
            },
        ),
    ]
