# Generated by Django 5.0.1 on 2026-01-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0006_studynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='studynote',
            name='highlights',
            field=models.JSONField(blank=True, help_text='List of highlighted text portions with start/end offsets', null=True),
        ),
    ]
