# Generated by Django 5.0.1 on 2026-01-13 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_featured_order_book_is_featured'),
        ('reading', '0007_studynote_highlights'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('definition', models.TextField()),
                ('context', models.TextField(blank=True, help_text='Example sentence')),
                ('book_title', models.CharField(blank=True, max_length=500)),
                ('book_author', models.CharField(blank=True, max_length=500)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('mastery', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('mastered', 'Mastered')], default='new', max_length=20)),
                ('review_count', models.IntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocabulary_words', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vocabulary Word',
                'verbose_name_plural': 'Vocabulary Words',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='reading_voc_user_id_dd51dc_idx'), models.Index(fields=['user', 'mastery'], name='reading_voc_user_id_e1201c_idx'), models.Index(fields=['word'], name='reading_voc_word_b90677_idx')],
            },
        ),
    ]
