# Generated by Django 5.0.1 on 2026-01-29 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0008_vocabularyword"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbook",
            name="replaced_by",
            field=models.ForeignKey(
                blank=True,
                help_text="If user switched to different edition, points to new UserBook",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replaces",
                to="reading.userbook",
            ),
        ),
    ]
