# Generated by Django 5.0.1 on 2026-02-22 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_populate_author_slugs'),
        ('reading', '0009_userbook_replaced_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='is_owned',
            field=models.BooleanField(default=False, help_text='User physically owns this book'),
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['user', 'is_owned'], name='reading_use_user_id_5844b3_idx'),
        ),
    ]
