# Generated by Django 5.0.1 on 2026-02-22 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_populate_author_slugs'),
        ('reading', '0010_userbook_is_owned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='is_wishlisted',
            field=models.BooleanField(default=False, help_text='User wishes to own this book (visible to friends as gift ideas)'),
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['user', 'is_wishlisted'], name='reading_use_user_id_d857e6_idx'),
        ),
    ]
