# Generated by Django 5.0.1 on 2026-03-15 19:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0011_userbook_is_wishlisted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        help_text="Total active reading time in seconds (excluding pauses)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "start_page",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "end_page",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "pages_read",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(help_text="When the session started"),
                ),
                ("ended_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_sessions",
                        to="reading.userbook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reading Session",
                "verbose_name_plural": "Reading Sessions",
                "ordering": ["-ended_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-ended_at"],
                        name="reading_rea_user_id_d7e1da_idx",
                    ),
                    models.Index(
                        fields=["user_book"], name="reading_rea_user_bo_4787b1_idx"
                    ),
                ],
            },
        ),
    ]
