# Generated by Django 5.0.1 on 2026-03-15 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_book_pages'),
        ('reading', '0012_add_reading_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='finished_at',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='vocabularyword',
            index=models.Index(fields=['user', 'book'], name='reading_voc_user_id_babfd8_idx'),
        ),
    ]
