# Generated by Django 5.0.1 on 2025-11-30 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "target_books",
                    models.IntegerField(
                        help_text="Target number of books to read",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "min_pages",
                    models.IntegerField(
                        blank=True,
                        help_text="Minimum pages per book to count",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this challenge currently active?"
                    ),
                ),
                (
                    "completed_books",
                    models.IntegerField(
                        default=0,
                        help_text="Number of books completed (auto-calculated)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Share challenge progress publicly"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "genre_filter",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Only count books from these genres",
                        to="books.genre",
                    ),
                ),
                (
                    "tag_filter",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Only count books with these tags",
                        to="books.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reading Challenge",
                "verbose_name_plural": "Reading Challenges",
                "ordering": ["-start_date"],
            },
        ),
    ]
