# Generated by Django 5.0.1 on 2025-11-30 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Circle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "max_members",
                    models.IntegerField(
                        default=10,
                        help_text="Maximum number of members (default: 10)",
                        validators=[django.core.validators.MaxValueValidator(20)],
                    ),
                ),
                (
                    "is_invite_only",
                    models.BooleanField(
                        default=True, help_text="Members can only join by invitation"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="circles/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Circle",
                "verbose_name_plural": "Circles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CircleComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Circle Comment",
                "verbose_name_plural": "Circle Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CircleInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Circle Invitation",
                "verbose_name_plural": "Circle Invitations",
            },
        ),
        migrations.CreateModel(
            name="CircleMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("member", "Member")],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Circle Membership",
                "verbose_name_plural": "Circle Memberships",
            },
        ),
        migrations.CreateModel(
            name="CirclePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("quote", "Quote Share"),
                            ("recommendation", "Book Recommendation"),
                            ("discussion", "Discussion"),
                            ("update", "Reading Update"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Post text/message")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Circle Post",
                "verbose_name_plural": "Circle Posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feed_type",
                    models.CharField(
                        choices=[
                            ("book_finished", "Book Finished"),
                            ("quote_added", "Quote Added"),
                            ("circle_post", "Circle Post"),
                            ("friend_joined", "Friend Joined"),
                            ("list_created", "List Created"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        help_text="Model name (Quote, CirclePost, UserBook, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(help_text="ID of the related object"),
                ),
                (
                    "preview_text",
                    models.TextField(blank=True, help_text="Cached preview text"),
                ),
                (
                    "preview_image",
                    models.URLField(blank=True, help_text="Cached image URL"),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Has user seen this feed item?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Feed Item",
                "verbose_name_plural": "Feed Items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Friendship",
                "verbose_name_plural": "Friendships",
            },
        ),
    ]
