# Generated by Django 5.0.1 on 2025-11-30 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        ("reading", "0002_initial"),
        ("social", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="circle",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_circles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circlecomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="circle_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circleinvitation",
            name="circle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="social.circle",
            ),
        ),
        migrations.AddField(
            model_name="circleinvitation",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_circle_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circleinvitation",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_circle_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circlemembership",
            name="circle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="social.circle",
            ),
        ),
        migrations.AddField(
            model_name="circlemembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="circle",
            name="members",
            field=models.ManyToManyField(
                related_name="circles",
                through="social.CircleMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circlepost",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="circle_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circlepost",
            name="book",
            field=models.ForeignKey(
                blank=True,
                help_text="Referenced book",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="books.book",
            ),
        ),
        migrations.AddField(
            model_name="circlepost",
            name="circle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="social.circle",
            ),
        ),
        migrations.AddField(
            model_name="circlepost",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                help_text="Shared quote",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reading.quote",
            ),
        ),
        migrations.AddField(
            model_name="circlecomment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="social.circlepost",
            ),
        ),
        migrations.AddField(
            model_name="feeditem",
            name="actor",
            field=models.ForeignKey(
                help_text="User who performed the action",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performed_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feeditem",
            name="user",
            field=models.ForeignKey(
                help_text="User who sees this in their feed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="friendship",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_friend_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="friendship",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_friend_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="circleinvitation",
            unique_together={("circle", "to_user")},
        ),
        migrations.AlterUniqueTogether(
            name="circlemembership",
            unique_together={("user", "circle")},
        ),
        migrations.AddIndex(
            model_name="feeditem",
            index=models.Index(
                fields=["user", "-created_at"], name="social_feed_user_id_b910e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feeditem",
            index=models.Index(
                fields=["user", "is_read"], name="social_feed_user_id_486c49_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="friendship",
            unique_together={("from_user", "to_user")},
        ),
    ]
