# Generated by Django 5.0.1 on 2025-12-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='feed_type',
            field=models.CharField(choices=[('book_finished', 'Book Finished'), ('progress_update', 'Progress Update'), ('quote_added', 'Quote Added'), ('circle_post', 'Circle Post'), ('friend_joined', 'Friend Joined'), ('list_created', 'List Created')], max_length=30),
        ),
    ]
