# Generated by Django 5.0.1 on 2026-01-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='feed_type',
            field=models.CharField(choices=[('book_finished', 'Book Finished'), ('book_started', 'Book Started'), ('progress_update', 'Progress Update'), ('quote_added', 'Quote Added'), ('circle_post', 'Circle Post'), ('friend_joined', 'Friend Joined'), ('list_created', 'List Created')], max_length=30),
        ),
    ]
