# Generated by Django 5.0.1 on 2026-02-01 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_add_slug_to_book'),
        ('reading', '0009_userbook_replaced_by'),
        ('social', '0005_alter_feeditem_feed_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='feed_type',
            field=models.CharField(choices=[('book_finished', 'Book Finished'), ('book_started', 'Book Started'), ('want_to_read', 'Want to Read'), ('progress_update', 'Progress Update'), ('quote_added', 'Quote Added'), ('circle_post', 'Circle Post'), ('friend_joined', 'Friend Joined'), ('list_created', 'List Created')], max_length=30),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_preview', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('subject', models.CharField(blank=True, help_text='Optional subject line', max_length=200)),
                ('is_important', models.BooleanField(default=False, help_text='Starred/important message')),
                ('read_at', models.DateTimeField(blank=True, help_text='When recipient read the message', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attached_book', models.ForeignKey(blank=True, help_text='Attached book recommendation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_attachments', to='books.book')),
                ('attached_quote', models.ForeignKey(blank=True, help_text='Attached quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_attachments', to='reading.quote')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='social_mess_convers_aca3c1_idx'), models.Index(fields=['sender', '-created_at'], name='social_mess_sender__b8bb77_idx')],
            },
        ),
    ]
