# Generated by Django 5.0.1 on 2026-02-03 20:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_add_slug_to_book"),
        ("reading", "0009_userbook_replaced_by"),
        ("social", "0006_add_messaging_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="circle",
            name="accent_color",
            field=models.CharField(
                default="#6366f1", help_text="Hex color for club branding", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="circle",
            name="current_book",
            field=models.ForeignKey(
                blank=True,
                help_text="Current book being read by the club",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_clubs",
                to="books.book",
            ),
        ),
        migrations.AlterField(
            model_name="circle",
            name="max_members",
            field=models.IntegerField(
                default=10,
                help_text="Maximum number of members",
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_follower", "New Follower"),
                    ("circle_invitation", "Circle Invitation"),
                    ("circle_post", "New Circle Post"),
                    ("comment", "New Comment"),
                    ("new_topic", "New Discussion Topic"),
                    ("topic_reply", "Topic Reply"),
                    ("new_club_book", "New Club Book"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="DiscussionTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General Discussion"),
                            ("spoilers", "Spoilers"),
                            ("theories", "Theories"),
                            ("characters", "Characters"),
                            ("themes", "Themes"),
                            ("quotes", "Favorite Quotes"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, help_text="Is this topic locked behind progress?"
                    ),
                ),
                (
                    "required_progress",
                    models.IntegerField(
                        default=0, help_text="Required reading progress (%) to unlock"
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discussion_topics",
                        to="books.book",
                    ),
                ),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="social.circle",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_topics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Discussion Topic",
                "verbose_name_plural": "Discussion Topics",
                "ordering": ["-is_pinned", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TopicMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("likes_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attached_book",
                    models.ForeignKey(
                        blank=True,
                        help_text="Attached book reference",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="topic_message_attachments",
                        to="books.book",
                    ),
                ),
                (
                    "attached_quote",
                    models.ForeignKey(
                        blank=True,
                        help_text="Attached quote",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="topic_messages",
                        to="reading.quote",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="social.discussiontopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic Message",
                "verbose_name_plural": "Topic Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TopicMessageLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="social.topicmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_message_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic Message Like",
                "verbose_name_plural": "Topic Message Likes",
            },
        ),
        migrations.CreateModel(
            name="BookClubReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("current", "Currently Reading"),
                            ("completed", "Completed"),
                            ("upcoming", "Upcoming"),
                        ],
                        default="current",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_readings",
                        to="books.book",
                    ),
                ),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_readings",
                        to="social.circle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Club Reading",
                "verbose_name_plural": "Book Club Readings",
                "ordering": ["-start_date", "-created_at"],
                "unique_together": {("circle", "book")},
            },
        ),
        migrations.AddIndex(
            model_name="topicmessage",
            index=models.Index(
                fields=["topic", "created_at"], name="social_topi_topic_i_5b4914_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="topicmessagelike",
            unique_together={("message", "user")},
        ),
    ]
