# Generated by Django 5.0.1 on 2026-02-14 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0009_userbook_replaced_by'),
        ('social', '0008_feeditem_comments_count_feeditem_likes_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to=settings.AUTH_USER_MODEL)),
                ('user_book', models.ForeignKey(help_text='The review (UserBook) being commented on', on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='reading.userbook')),
            ],
            options={
                'verbose_name': 'Review Comment',
                'verbose_name_plural': 'Review Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_likes', to=settings.AUTH_USER_MODEL)),
                ('user_book', models.ForeignKey(help_text='The review (UserBook) being liked', on_delete=django.db.models.deletion.CASCADE, related_name='review_likes', to='reading.userbook')),
            ],
            options={
                'verbose_name': 'Review Like',
                'verbose_name_plural': 'Review Likes',
                'unique_together': {('user_book', 'user')},
            },
        ),
    ]
