# Generated by Django 5.0.1 on 2026-02-17 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_install_unaccent_extension'),
        ('social', '0009_reviewcomment_reviewlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmessage',
            name='attachment_image',
            field=models.ImageField(blank=True, help_text='Image attachment', null=True, upload_to='topic_messages/'),
        ),
        migrations.AddField(
            model_name='topicmessage',
            name='mentions',
            field=models.JSONField(blank=True, default=list, help_text='List of mentioned user IDs'),
        ),
        migrations.AddField(
            model_name='topicmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='Parent message this is replying to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='social.topicmessage'),
        ),
        migrations.AlterField(
            model_name='discussiontopic',
            name='category',
            field=models.CharField(choices=[('general', 'General Discussion'), ('spoilers', 'Spoilers'), ('theories', 'Theories'), ('characters', 'Characters'), ('themes', 'Themes'), ('quotes', 'Favorite Quotes'), ('polls', 'Polls'), ('announcements', 'Announcements')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('poll_type', models.CharField(choices=[('book_vote', 'Book Vote'), ('schedule', 'Schedule Vote'), ('general', 'General Poll')], default='general', max_length=20)),
                ('allows_multiple', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='social.discussiontopic')),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('book', models.ForeignKey(blank=True, help_text='For book vote polls', null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='social.poll')),
            ],
            options={
                'verbose_name': 'Poll Option',
                'verbose_name_plural': 'Poll Options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('heart', 'Heart'), ('thumbsup', 'Thumbs Up'), ('fire', 'Fire'), ('thinking', 'Thinking'), ('clap', 'Clap'), ('lightbulb', 'Lightbulb'), ('book', 'Book'), ('sparkles', 'Sparkles')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='social.topicmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Reaction',
                'verbose_name_plural': 'Message Reactions',
                'unique_together': {('message', 'user', 'emoji')},
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='social.polloption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poll Vote',
                'verbose_name_plural': 'Poll Votes',
                'unique_together': {('option', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TopicReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='social.discussiontopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_read_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topic Read Status',
                'verbose_name_plural': 'Topic Read Statuses',
                'indexes': [models.Index(fields=['user', 'topic'], name='social_topi_user_id_d7e441_idx')],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
