# Generated by Django 5.0.1 on 2026-02-17 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_install_unaccent_extension'),
        ('social', '0010_topicmessage_attachment_image_topicmessage_mentions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Visible in circle discovery'),
        ),
        migrations.CreateModel(
            name='CircleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('milestone', 'Reading Milestone'), ('discussion', 'Discussion Session'), ('deadline', 'Reading Deadline')], default='milestone', max_length=20)),
                ('event_date', models.DateTimeField()),
                ('target_progress', models.IntegerField(default=0, help_text='Target reading progress percentage (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circle_events', to='books.book')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='social.circle')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_circle_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
