# Generated by Django 5.0.1 on 2026-02-17 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0009_userbook_replaced_by'),
        ('social', '0011_circle_is_public_circleevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attached_study_note',
            field=models.ForeignKey(blank=True, help_text='Attached study note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_attachments', to='reading.studynote'),
        ),
    ]
