# Generated by Django 5.0.1 on 2026-02-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_add_attached_study_note_to_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmessage',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
