# Generated by Django 5.0.1 on 2026-02-20 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_populate_author_slugs'),
        ('reading', '0009_userbook_replaced_by'),
        ('social', '0013_add_is_pinned_to_topicmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicmessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='topicmessage',
            index=models.Index(fields=['topic', 'updated_at'], name='social_topi_topic_i_a53e12_idx'),
        ),
    ]
