# Generated by Django 5.0.1 on 2025-11-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReadingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "is_smart",
                    models.BooleanField(
                        default=False, help_text="Auto-populate based on filter rules"
                    ),
                ),
                (
                    "filter_rules",
                    models.JSONField(
                        blank=True,
                        help_text="Filter criteria for smart lists",
                        null=True,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Make list visible to everyone"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Reading List",
                "verbose_name_plural": "Reading Lists",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ReadingListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Manual ordering within the list"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Personal note about why this book is in the list",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Reading List Item",
                "verbose_name_plural": "Reading List Items",
                "ordering": ["order", "-added_at"],
            },
        ),
    ]
