# Generated by Django 5.0.1 on 2025-11-30 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        ("lists", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="readinglist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reading_lists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="readinglistitem",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="list_items",
                to="books.book",
            ),
        ),
        migrations.AddField(
            model_name="readinglistitem",
            name="reading_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="lists.readinglist",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="readinglist",
            unique_together={("user", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="readinglistitem",
            unique_together={("reading_list", "book")},
        ),
    ]
