# Generated by Django 5.0.1 on 2026-01-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='featured_order',
            field=models.IntegerField(default=0, help_text='Order for featured books (lower = higher priority)'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark as featured book for cold start/discovery'),
        ),
    ]
