# Generated by Django 5.0.1 on 2026-01-24 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_featured_order_book_is_featured'),
        ('reading', '0008_vocabularyword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pace', models.FloatField(default=0.5, help_text='0=slow/contemplative, 1=fast/page-turner')),
                ('complexity', models.FloatField(default=0.5, help_text='0=simple/accessible, 1=dense/challenging')),
                ('emotional_intensity', models.FloatField(default=0.5, help_text='0=light/easy, 1=heavy/intense')),
                ('darkness', models.FloatField(default=0.5, help_text='0=hopeful/light, 1=dark/bleak')),
                ('character_focus', models.FloatField(default=0.5, help_text='0=plot-driven, 1=character-driven')),
                ('introspection', models.FloatField(default=0.5, help_text='0=action/external, 1=introspective/philosophical')),
                ('themes', models.JSONField(blank=True, default=list, help_text="List of theme slugs: ['faith', 'identity', 'suffering']")),
                ('source', models.CharField(choices=[('user_votes', 'User Votes Aggregated'), ('ai_generated', 'AI Generated'), ('manual', 'Manual Entry')], default='manual', max_length=20)),
                ('vote_count', models.IntegerField(default=0, help_text='Number of user votes for these attributes')),
                ('confidence_score', models.FloatField(default=0.0, help_text='0-1, confidence in these values based on vote count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dna', to='books.book')),
            ],
            options={
                'verbose_name': 'Book DNA',
                'verbose_name_plural': 'Book DNAs',
            },
        ),
        migrations.CreateModel(
            name='BookDNAVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pace', models.FloatField(blank=True, null=True)),
                ('complexity', models.FloatField(blank=True, null=True)),
                ('emotional_intensity', models.FloatField(blank=True, null=True)),
                ('darkness', models.FloatField(blank=True, null=True)),
                ('character_focus', models.FloatField(blank=True, null=True)),
                ('introspection', models.FloatField(blank=True, null=True)),
                ('themes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dna_votes', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_dna_votes', to=settings.AUTH_USER_MODEL)),
                ('user_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dna_vote', to='reading.userbook')),
            ],
            options={
                'verbose_name': 'Book DNA Vote',
                'verbose_name_plural': 'Book DNA Votes',
                'unique_together': {('user', 'book')},
            },
        ),
    ]
