# Generated by Django 5.0.1 on 2026-01-29 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_add_book_dna_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_primary_edition",
            field=models.BooleanField(
                default=False, help_text="Primary edition for this book group"
            ),
        ),
        migrations.CreateModel(
            name="BookGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("canonical_title", models.CharField(max_length=500)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Best/longest description from editions"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("editions_count", models.IntegerField(default=0)),
                (
                    "canonical_authors",
                    models.ManyToManyField(
                        related_name="book_groups", to="books.author"
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Group",
                "verbose_name_plural": "Book Groups",
                "ordering": ["canonical_title"],
            },
        ),
        migrations.AddField(
            model_name="book",
            name="book_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Group linking different editions of the same work",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="editions",
                to="books.bookgroup",
            ),
        ),
        migrations.CreateModel(
            name="BookGroupDNA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pace",
                    models.FloatField(
                        default=0.5,
                        help_text="0=slow/contemplative, 1=fast/page-turner",
                    ),
                ),
                (
                    "complexity",
                    models.FloatField(
                        default=0.5,
                        help_text="0=simple/accessible, 1=dense/challenging",
                    ),
                ),
                (
                    "emotional_intensity",
                    models.FloatField(
                        default=0.5, help_text="0=light/easy, 1=heavy/intense"
                    ),
                ),
                (
                    "darkness",
                    models.FloatField(
                        default=0.5, help_text="0=hopeful/light, 1=dark/bleak"
                    ),
                ),
                (
                    "character_focus",
                    models.FloatField(
                        default=0.5, help_text="0=plot-driven, 1=character-driven"
                    ),
                ),
                (
                    "introspection",
                    models.FloatField(
                        default=0.5,
                        help_text="0=action/external, 1=introspective/philosophical",
                    ),
                ),
                (
                    "themes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of theme slugs: ['faith', 'identity', 'suffering']",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user_votes", "User Votes Aggregated"),
                            ("ai_generated", "AI Generated"),
                            ("manual", "Manual Entry"),
                            ("migrated", "Migrated from Book"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "vote_count",
                    models.IntegerField(
                        default=0, help_text="Number of user votes for these attributes"
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="0-1, confidence in these values based on vote count",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book_group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dna",
                        to="books.bookgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Group DNA",
                "verbose_name_plural": "Book Group DNAs",
            },
        ),
    ]
