# Generated by Django 5.0.1 on 2026-02-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_book_is_primary_edition_bookgroup_book_book_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(blank=True, max_length=550),
        ),
    ]
