# Generated by Django 5.0.1 on 2026-02-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_add_slug_to_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdna',
            name='genre_tags',
            field=models.JSONField(blank=True, default=list, help_text="Genre tag slugs: ['literary_fiction', 'sci_fi']"),
        ),
        migrations.AddField(
            model_name='bookdna',
            name='primary_themes',
            field=models.JSONField(blank=True, default=list, help_text='Top 3 primary theme slugs (higher weight)'),
        ),
        migrations.AddField(
            model_name='bookdnavote',
            name='genre_tags',
            field=models.JSONField(blank=True, default=list, help_text='Genre tag slugs selected by user'),
        ),
        migrations.AddField(
            model_name='bookdnavote',
            name='primary_themes',
            field=models.JSONField(blank=True, default=list, help_text='Up to 3 primary theme slugs (higher weight)'),
        ),
        migrations.AddField(
            model_name='bookgroupdna',
            name='genre_tags',
            field=models.JSONField(blank=True, default=list, help_text="Genre tag slugs: ['literary_fiction', 'sci_fi']"),
        ),
        migrations.AddField(
            model_name='bookgroupdna',
            name='primary_themes',
            field=models.JSONField(blank=True, default=list, help_text='Top 3 primary theme slugs (higher weight)'),
        ),
    ]
