# Generated by Django 5.0.1 on 2026-02-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_bookdna_genre_tags_bookdna_primary_themes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdna',
            name='primary_genre_tag',
            field=models.CharField(blank=True, help_text='Single primary genre tag slug', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookdnavote',
            name='primary_genre_tag',
            field=models.CharField(blank=True, help_text='Single primary genre tag slug', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookgroupdna',
            name='primary_genre_tag',
            field=models.CharField(blank=True, help_text='Single primary genre tag slug', max_length=50, null=True),
        ),
    ]
