# Generated by Django 5.0.1 on 2026-02-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_install_unaccent_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="slug",
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
