# Generated by Django 5.0.1 on 2026-02-17 20:59

from django.db import migrations
from django.utils.text import slugify


def populate_author_slugs(apps, schema_editor):
    Author = apps.get_model('books', 'Author')
    for author in Author.objects.filter(slug=''):
        author.slug = slugify(author.name) or f"author-{author.pk}"
        author.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_add_slug_to_author"),
    ]

    operations = [
        migrations.RunPython(populate_author_slugs, migrations.RunPython.noop),
    ]
