# Generated by Django 5.0.1 on 2026-02-22 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0010_populate_author_slugs"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("canonical_name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Author Group",
                "verbose_name_plural": "Author Groups",
                "ordering": ["canonical_name"],
            },
        ),
        migrations.AddField(
            model_name="author",
            name="is_primary_alias",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="author",
            name="author_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="books.authorgroup",
            ),
        ),
    ]
