# Generated by Django 5.0.1 on 2026-02-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_authorgroup_and_author_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
