# Generated by Django 5.0.1 on 2026-02-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_author_photo_max_length_500'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='wikidata_id',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
