# Generated by Django 5.0.1 on 2026-02-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0014_author_last_modified_by_book_last_modified_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("google_books", "Google Books API"),
                    ("open_library", "Open Library API"),
                    ("hardcover", "Hardcover.app"),
                    ("delfi_scrape", "Delfi Scrape"),
                    ("vulkan_scrape", "Vulkan Scrape"),
                    ("laguna_scrape", "Laguna Scrape"),
                ],
                default="manual",
                max_length=50,
            ),
        ),
    ]
