# Generated by Django 5.0.1 on 2026-02-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DismissedAuthorPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author1_id', models.IntegerField()),
                ('author2_id', models.IntegerField()),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('author1_id', 'author2_id')},
            },
        ),
    ]
