# Generated by Django 5.0.1 on 2026-02-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DismissedBookPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book1_id', models.IntegerField()),
                ('book2_id', models.IntegerField()),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('book1_id', 'book2_id')},
            },
        ),
    ]
