# Generated by Django 5.0.1 on 2026-02-24 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('category', models.CharField(choices=[('activity', 'Activity'), ('quality', 'Quality'), ('special', 'Special'), ('founding', 'Founding')], max_length=12)),
                ('auto_criteria', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContributionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('quote_added', 'Quote Added'), ('vocabulary_added', 'Vocabulary Added'), ('study_note_added', 'Study Note Added'), ('review_written', 'Review Written'), ('reading_list_created', 'List Created'), ('dna_vote_cast', 'DNA Vote Cast'), ('circle_post_created', 'Circle Post'), ('discussion_created', 'Discussion Created'), ('topic_message_posted', 'Message Posted'), ('author_linked', 'Authors Linked'), ('author_unlinked', 'Author Unlinked'), ('author_bio_added', 'Author Bio Added'), ('author_pair_dismissed', 'Pair Dismissed'), ('book_metadata_edited', 'Book Edited'), ('data_issue_resolved', 'Issue Resolved'), ('book_finished', 'Book Finished'), ('challenge_completed', 'Challenge Done')], db_index=True, max_length=40)),
                ('content_type', models.CharField(max_length=50)),
                ('object_id', models.IntegerField()),
                ('category', models.CharField(choices=[('content', 'Content Creation'), ('community', 'Community Participation'), ('curation', 'Data Curation'), ('reading', 'Reading Activity')], max_length=20)),
                ('base_points', models.IntegerField()),
                ('awarded_points', models.IntegerField()),
                ('previous_state', models.JSONField(blank=True, null=True)),
                ('is_reverted', models.BooleanField(default=False)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('quality_status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='unreviewed', max_length=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_contributions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributionFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_contributions', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='contributions.contributionlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_badges', to=settings.AUTH_USER_MODEL)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='contributions.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_points', models.IntegerField(default=0)),
                ('community_points', models.IntegerField(default=0)),
                ('curation_points', models.IntegerField(default=0)),
                ('reading_points', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(db_index=True, default=0)),
                ('total_contributions', models.IntegerField(default=0)),
                ('approved_count', models.IntegerField(default=0)),
                ('flagged_count', models.IntegerField(default=0)),
                ('rejected_count', models.IntegerField(default=0)),
                ('quality_ratio', models.FloatField(default=1.0)),
                ('tier', models.CharField(choices=[('reader', 'Reader'), ('contributor', 'Contributor'), ('curator', 'Curator'), ('moderator', 'Moderator')], default='reader', max_length=12)),
                ('tier_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_tier_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_points'],
            },
        ),
        migrations.AddIndex(
            model_name='contributionlog',
            index=models.Index(fields=['user', '-created_at'], name='contributio_user_id_866cea_idx'),
        ),
        migrations.AddIndex(
            model_name='contributionlog',
            index=models.Index(fields=['action', '-created_at'], name='contributio_action_f55848_idx'),
        ),
        migrations.AddIndex(
            model_name='contributionlog',
            index=models.Index(fields=['quality_status'], name='contributio_quality_6ba809_idx'),
        ),
        migrations.AddIndex(
            model_name='contributionlog',
            index=models.Index(fields=['content_type', 'object_id'], name='contributio_content_d949b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
    ]
