# Generated by Django 5.0.1 on 2026-02-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionlog',
            name='action',
            field=models.CharField(choices=[('quote_added', 'Quote Added'), ('vocabulary_added', 'Vocabulary Added'), ('study_note_added', 'Study Note Added'), ('review_written', 'Review Written'), ('reading_list_created', 'List Created'), ('book_imported', 'Book Imported'), ('book_added_manual', 'Book Added Manually'), ('dna_vote_cast', 'DNA Vote Cast'), ('circle_post_created', 'Circle Post'), ('discussion_created', 'Discussion Created'), ('topic_message_posted', 'Message Posted'), ('author_linked', 'Authors Linked'), ('author_unlinked', 'Author Unlinked'), ('author_bio_added', 'Author Bio Added'), ('author_pair_dismissed', 'Pair Dismissed'), ('book_metadata_edited', 'Book Edited'), ('data_issue_resolved', 'Issue Resolved'), ('books_linked', 'Books Linked'), ('book_pair_dismissed', 'Book Pair Dismissed'), ('book_finished', 'Book Finished'), ('challenge_completed', 'Challenge Done')], db_index=True, max_length=40),
        ),
    ]
